// ไฟล์นี้ถูกสร้างอัตโนมัติโดย scripts/generate-toast-gif-manifest.mjs — ห้ามแก้ด้วยมือ
import type { ToastGifCategory } from "./toast-gif"

export const TOAST_GIF_FILES: Record<ToastGifCategory, string[]> = {
  welcome: [
    "Americas Got Talent Reaction GIF by Top Talent.webp",
    "Austin Powers Doctor Evil GIF.webp",
    "Cat Hello GIF.webp",
    "Cat Sup GIF.webp",
    "Cat Working GIF.webp",
    "Cookie Monster Hello GIF by Sesame Street.webp",
    "Dog Reaction GIF.webp",
    "Dogs Wave Hi GIF by MOODMAN.webp",
    "Elmo Hello GIF by Sesame Street.webp",
    "Episode 15 Hello GIF by SpongeBob SquarePants.webp",
    "GIF by Teletubbies.webp",
    "Good Morning Hello GIF by Teletubbies (1).webp",
    "Good Morning Hello GIF by Teletubbies (2).webp",
    "Good Morning Hello GIF by Teletubbies.webp",
    "Goofy Movie Hello GIF.webp",
    "Hai Hello GIF.webp",
    "Happy Korean Drama GIF by The Swoon (1).webp",
    "Happy Korean Drama GIF by The Swoon.webp",
    "Hey You Hello GIF by Regal.webp",
    "Inside Out Hello GIF by Disney Pixar.webp",
    "Its Me Hello GIF.webp",
    "Jimmy Fallon Hello GIF.webp",
    "Little Boy Reaction GIF by Children's Miracle Network Hospitals.webp",
    "Martial Arts Reaction GIF by Arrow Video.webp",
    "Moving Pictures Hello GIF.webp",
    "New World Wow GIF by Disney Pixar.webp",
    "Nicki Minaj Hello GIF by DNCE.webp",
    "Penguin Hello GIF.webp",
    "Sailor Moon Hello GIF.webp",
    "season 2 hello GIF by SpongeBob SquarePants.webp",
    "season 3 krabby land GIF by SpongeBob SquarePants.webp",
    "See You Later Hello GIF by Teletubbies (1).webp",
    "See You Later Hello GIF by Teletubbies.webp",
    "Spider-Man Hello GIF by MOODMAN.webp",
    "Stitch Hi Everyone GIF.webp",
    "T Rex Hello GIF.webp",
    "T-Rex Hello GIF by Rooster Teeth.webp",
    "The Office GIF by DAZN.webp",
    "Tom Hanks Hello GIF.webp",
    "Tonight Show Hello GIF by The Tonight Show Starring Jimmy Fallon.webp",
    "wave hello GIF (1).webp",
    "Wave Hello GIF (2).webp",
    "Wave Hello GIF (3).webp",
    "Wave Hello GIF.webp",
    "Waving San Diego Zoo GIF by San Diego Zoo Wildlife Alliance.webp",
    "welcome back minions GIF.webp",
    "Welcome Home GIF.webp",
    "Welcome Home Yo GIF by Bombay Softwares.webp",
    "Welcome To The Team GIF by MOODMAN.webp",
    "Welcome To The Team Hello GIF by Originals.webp",
    "Whats Up Hello GIF.webp",
    "White Cat Hello GIF.webp",
    "Youre Back Jimmy Fallon GIF by The Tonight Show Starring Jimmy Fallon.webp",
    "Youtube Hello GIF (1).webp",
    "Youtube Hello GIF.webp",
  ],
  success: [
    "check.svg",
    "confetti.svg",
  ],
  delete: [
    "sweep.svg",
    "trash.svg",
  ],
  error: [
    "alert.svg",
    "cross.svg",
  ],
}
