// ไฟล์นี้ถูกสร้างอัตโนมัติโดย scripts/generate-toast-gif-manifest.mjs — ห้ามแก้ด้วยมือ
import type { ToastGifCategory } from "./toast-gif"

export const TOAST_GIF_FILES: Record<ToastGifCategory, string[]> = {
  welcome: [
    "Americas Got Talent Reaction GIF by Top Talent.webp",
    "Austin Powers Doctor Evil GIF.webp",
    "Cat Hello GIF.webp",
    "Cat Sup GIF.webp",
    "Cat Working GIF.webp",
    "Cookie Monster Hello GIF by Sesame Street.webp",
    "Dog Reaction GIF.webp",
    "Dogs Wave Hi GIF by MOODMAN.webp",
    "Elmo Hello GIF by Sesame Street.webp",
    "Episode 15 Hello GIF by SpongeBob SquarePants.webp",
    "GIF by Teletubbies.webp",
    "Good Morning Hello GIF by Teletubbies (1).webp",
    "Good Morning Hello GIF by Teletubbies (2).webp",
    "Good Morning Hello GIF by Teletubbies.webp",
    "Goofy Movie Hello GIF.webp",
    "Hai Hello GIF.webp",
    "Happy Korean Drama GIF by The Swoon (1).webp",
    "Happy Korean Drama GIF by The Swoon.webp",
    "Hey You Hello GIF by Regal.webp",
    "Inside Out Hello GIF by Disney Pixar.webp",
    "Its Me Hello GIF.webp",
    "Jimmy Fallon Hello GIF.webp",
    "Little Boy Reaction GIF by Children's Miracle Network Hospitals.webp",
    "Martial Arts Reaction GIF by Arrow Video.webp",
    "Moving Pictures Hello GIF.webp",
    "New World Wow GIF by Disney Pixar.webp",
    "Nicki Minaj Hello GIF by DNCE.webp",
    "Penguin Hello GIF.webp",
    "Sailor Moon Hello GIF.webp",
    "season 2 hello GIF by SpongeBob SquarePants.webp",
    "season 3 krabby land GIF by SpongeBob SquarePants.webp",
    "See You Later Hello GIF by Teletubbies (1).webp",
    "See You Later Hello GIF by Teletubbies.webp",
    "Spider-Man Hello GIF by MOODMAN.webp",
    "Stitch Hi Everyone GIF.webp",
    "T Rex Hello GIF.webp",
    "T-Rex Hello GIF by Rooster Teeth.webp",
    "The Office GIF by DAZN.webp",
    "Tom Hanks Hello GIF.webp",
    "wave hello GIF (1).webp",
    "Wave Hello GIF (2).webp",
    "Wave Hello GIF (3).webp",
    "Wave Hello GIF.webp",
    "Waving San Diego Zoo GIF by San Diego Zoo Wildlife Alliance.webp",
    "welcome back minions GIF.webp",
    "Welcome Home GIF.webp",
    "Welcome To The Team GIF by MOODMAN.webp",
    "Welcome To The Team Hello GIF by Originals.webp",
    "Whats Up Hello GIF.webp",
    "White Cat Hello GIF.webp",
    "Youre Back Jimmy Fallon GIF by The Tonight Show Starring Jimmy Fallon.webp",
    "Youtube Hello GIF (1).webp",
    "Youtube Hello GIF.webp",
  ],
  success: [
    "Approve South Park GIF.webp",
    "Baby Success GIF.webp",
    "Bob Esponja GIF by Nickelodeon LATAM.webp",
    "brent rambo thumbs up GIF.webp",
    "Cartoon Thumbs Up GIF by SpongeBob SquarePants.webp",
    "Do It Reaction GIF by Muta Bor Studio.webp",
    "Dragon Ball Z Ok GIF by slicedbread.webp",
    "Excited Season 5 GIF by SpongeBob SquarePants.webp",
    "Excited Yes Please GIF.webp",
    "K-Pop Reaction GIF.webp",
    "K-Pop Yes GIF.webp",
    "Look At Me Cooking GIF by Pingu.webp",
    "My Work Is Done Wipe Hands Off GIF by SpongeBob SquarePants.webp",
    "Nickelodeon Thumbs Up GIF by SpongeBob SquarePants.webp",
    "Nickelodeon Yes GIF by SpongeBob SquarePants.webp",
    "Noice Thats Nice GIF.webp",
    "Scream Help GIF.webp",
    "season 9 episode 10 GIF by SpongeBob SquarePants.webp",
    "Shaun The Sheep Movie Ok GIF.webp",
    "Shaun The Sheep Yes GIF by Aardman Animations.webp",
    "sponge bob GIF.webp",
    "Spongebob Squarepants Ok GIF.webp",
    "Spongebob Squarepants Thumbs Up GIF.webp",
    "Success GIF by DJ CHIMO BAYO.webp",
    "Success Kid GIF by MOODMAN.webp",
    "Task Thumbs Up GIF by Mailchimp.webp",
    "The Young Pope GIF.webp",
    "thumbs u approve GIF.webp",
    "Thumbs Up GIF.webp",
  ],
  delete: [
    "Animation Work GIF.webp",
    "apple goodbye GIF by isabellaauer.webp",
    "Bang No GIF by VPRO.webp",
    "Computer Delete GIF.webp",
    "Delete Barack Obama GIF by Obama.webp",
    "delete black and white GIF.webp",
    "Delete Get Out GIF by John Crist Comedy.webp",
    "Delete Just As I Thought GIF by Robert E Blackmon.webp",
    "Go Away No GIF by SuperSport.webp",
    "Old Lady Do Not Want GIF by Offline Granny!.webp",
    "panic typing GIF.webp",
    "Trash Can Falling GIF by America's Funniest Home Videos.webp",
    "Trash Can GIF.webp",
    "trash GIF.webp",
  ],
  error: [
    "Angry Blue Screen GIF by Pusch-Data GmbH.webp",
    "Angry Computer GIF.webp",
    "angry employee office destruction GIF.webp",
    "burning the it crowd GIF.webp",
    "computer computing GIF.webp",
    "Computer Error GIF by haydiroket (Mert Keskin).webp",
    "Computer Game Work GIF by TRT.webp",
    "computing GIF.webp",
    "Confused Too Much GIF by Bichi Mao.webp",
    "Digital Art Love GIF by systaime.webp",
    "Hair What GIF by TRT.webp",
    "loading GIF.webp",
    "Office Rage GIF by Sticos Oppslag.webp",
    "Over It No GIF by Unscreen.webp",
    "project coding GIF.webp",
    "Shocked Fire GIF.webp",
    "Technical Difficulties Error GIF.webp",
    "tela azul GIF.webp",
    "time board GIF.webp",
    "Warning T-Rex GIF by Meta Digital.webp",
    "Windows Error GIF.webp",
  ],
}
